import type { Player } from '../types/player'
import { representativeEvidence } from './youthOpportunities'
import { computeCurrentAbility, toOvr } from './rating'

export type SelectionStage = 'not-started' | 'longlist' | 'camp' | 'selected' | 'cut'
export interface SelectionBreakdown { eligible?:boolean; reason?:string; performance:number; ability:number; coachTrust:number; fitness:number; form:number; mentality:number; total:number; positionalRank:number; entrants:number; survivors:number }
export interface YouthPathwayState {
  ageGroup:'U15'|'U16'|'U17'|'U18'; schoolSquad:'first'|'reserve'|'development'|'released'; regionalSelection:SelectionStage; nationalSelection:SelectionStage
  regionalScore?:SelectionBreakdown; nationalScore?:SelectionBreakdown; sundayInterest:number; sundayStatus:'undiscovered'|'watched'|'training-invite'|'squad-offer'|'registered'; showcaseInvited:boolean
  academyTrialStatus:'none'|'invited'|'active'|'passed'|'failed'; academyTrialClubId?:string
  showcaseSeason?:number; recruitmentVersion?:number
}
export function ageGroupFor(age:number):YouthPathwayState['ageGroup'] { if(age<=14)return'U15'; if(age===15)return'U16'; if(age===16)return'U17'; return'U18' }
export function initYouthPathway(player:Player):YouthPathwayState { const schoolSquad=player.squadRole==='released'?'released':player.squadRole==='reserves'?'reserve':'first'; return { ageGroup:ageGroupFor(player.careerClock.ageYears),schoolSquad,regionalSelection:'not-started',nationalSelection:'not-started',sundayInterest:player.grassrootsPath==='sunday'?100:0,sundayStatus:player.grassrootsPath==='sunday'?'registered':'undiscovered',showcaseInvited:false,academyTrialStatus:'none',recruitmentVersion:1 } }
function average(values:number[]){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0}
export function representativeSelection(player:Player,level:'regional'|'national'):SelectionBreakdown { const recent=(player.matchRatings??[]).slice(level==='national'?-8:-6); const formAverage=average(recent); const performance=Math.max(0,Math.min(100,((formAverage||5.5)-4.5)*25)); const ability=Math.max(0,Math.min(100,(toOvr(computeCurrentAbility(player))-30)*2.2)); const trust=Math.max(0,Math.min(100,((player.coachTrust??0)+10)*5)); const fitness=Math.max(0,Math.min(100,player.fitness.stamina)); const form=Math.max(0,Math.min(100,((formAverage||5.5)-5)*33.3)); const mentality=Math.max(0,Math.min(100,((player.confidence?.value??0)+10)*5)); const total=Math.round(performance*.4+ability*.2+trust*.15+fitness*.1+form*.1+mentality*.05); const entrants=level==='regional'?60:35; const survivors=23; const positionalRank=Math.max(1,Math.min(level==='regional'?8:6,Math.ceil((100-total)/14))); return {...representativeEvidence(player,level),performance:Math.round(performance),ability:Math.round(ability),coachTrust:Math.round(trust),fitness:Math.round(fitness),form:Math.round(form),mentality:Math.round(mentality),total,positionalRank,entrants,survivors} }
export function selectionPassed(score:SelectionBreakdown,level:'regional'|'national'){return score.eligible===true&&score.total>=(level==='regional'?57:66)&&score.positionalRank<=(level==='regional'?4:3)}
export const MONTH_BY_WEEK=['January','January','January','February','February','February','February','March','March','March','March','April','April','April','April','May','May','May','May','June','June','June','June','July','July','July','July','August','August','August','August','September','September','September','September','October','October','October','October','November','November','November','December','December'] as const
export function monthForWeek(week:number){return MONTH_BY_WEEK[Math.max(0,Math.min(MONTH_BY_WEEK.length-1,week-1))]}
export function pathwayNextStep(player:Player){const s=player.pathway??initYouthPathway(player); if(player.careerClock.phase==='academy')return'Earn a professional contract'; if(player.communityTrialSessions!==undefined&&s.sundayStatus==='training-invite')return`Community trial: ${Math.min(3,player.communityTrialSessions)}/3 training sessions`; if(player.grassrootsPath==='sunday')return s.sundayStatus==='squad-offer'||!player.sundayContract?'Review your Sunday club offer':'Build Sunday League form for academy scouts'; if(s.regionalSelection==='not-started')return'Perform in school and Regional Cup football'; if(s.regionalSelection==='longlist')return'Regional XI selection camp'; if(s.regionalSelection==='camp')return'Regional XI final squad reveal'; if(s.regionalSelection==='selected'&&s.nationalSelection==='not-started')return'Represent your region at the National Schools Championship'; if(s.nationalSelection==='longlist'||s.nationalSelection==='camp')return'National schools squad reveal'; if(s.nationalSelection==='selected')return'International youth football'; return'Build form for the next selection window'}
