// AUDIT 19 (P59) — real bug found via systematic sweep: academyLeagueCup and
// academyKnockoutCup (both real, calendar.ts-defined academy cup
// competitions) were never checked by the XP tier-detection logic in
// Career.tsx — only the grassroots cup names were, so a real academy cup
// tie silently earned plain academy-tier XP instead of cup-tier XP. This
// reads the SAME source files the real game does (not a hand-copied list
// that could drift out of sync with them) and proves every competition ID
// calendar.ts actually generates is correctly classified.
import { readFileSync } from 'fs'

let fails = 0
const check = (c: boolean, m: string) => { if (!c) { fails++; console.error('  ✗', m) } else console.log('  ✓', m) }

console.log('\n[A] every real cup/league competition ID calendar.ts defines is checked by the tier-detection logic')
{
  const calendarSrc = readFileSync('src/engine/calendar.ts', 'utf-8')
  const careerSrc = readFileSync('src/screens/Career.tsx', 'utf-8')

  // Pull the real competition IDs straight from SCHOOL_ACTIVE,
  // SUNDAY_ACTIVE and ACADEMY_ACTIVE — the actual source of truth, not a
  // hand-maintained list here that could itself drift.
  const activeSetMatches = [...calendarSrc.matchAll(/const \w+_ACTIVE = new Set\(\[([^\]]+)\]\)/g)]
  check(activeSetMatches.length === 3, `found all three phase-active competition sets (${activeSetMatches.length})`)

  const allRealCompetitionIds = new Set<string>()
  for (const m of activeSetMatches) {
    const ids = [...m[1].matchAll(/'([^']+)'/g)].map((x) => x[1])
    for (const id of ids) allRealCompetitionIds.add(id)
  }
  check(allRealCompetitionIds.size >= 5, `found a real number of distinct competition IDs across both phases (${allRealCompetitionIds.size}): ${[...allRealCompetitionIds].join(', ')}`)

  // Pull the tier-detection ternary's own competitionId checks directly out
  // of Career.tsx, the same way — not a hand-maintained mirror list.
  const tierBlock = careerSrc.match(/const tier: import\('..\/engine\/xp'\)\.CompetitionTier =[\s\S]*?const matchXp/)?.[0] ?? ''
  const checkedIds = new Set([...tierBlock.matchAll(/mode\.competitionId === '([^']+)'/g)].map((m) => m[1]))

  const cupLike = [...allRealCompetitionIds].filter((id) => id.toLowerCase().includes('cup'))
  check(cupLike.length >= 4, `found the real cup-shaped competition IDs to verify (${cupLike.length}): ${cupLike.join(', ')}`)
  for (const id of cupLike) {
    check(checkedIds.has(id), `"${id}" (a real cup competition, generated by calendar.ts) is explicitly checked in the tier-detection logic — this is exactly the bug class that let academy cups silently earn the wrong XP tier`)
  }

  // Sanity check on the extraction itself — 'international' IS explicitly
  // checked in the real code, so if this fails, the regex extraction is
  // broken, not the game.
  check(checkedIds.has('international'), 'sanity check: the extraction itself correctly found the known "international" check — confirms this audit is reading real logic, not silently matching nothing')
}

console.log(fails === 0 ? '\n✅ AUDIT 19 PASSED' : `\n❌ AUDIT 19: ${fails} CHECK(S) FAILED`)
process.exit(fails ? 1 : 0)
